version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: falsafwan002
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: smart_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

